#!/bin/sh
name=$1

replace() {
  file=$1
  key=$2
  value=$3
  value=$(echo "$value" | sed -e 's#/#\\/#g' -e 's/&/\\\&/g')
  sed -i '' -e "s/{# *$key *#}/$value/g" $file
}

for file in $(find . -type f)
do
  replace "$file" name "$name"
done

mv lib_name.css "$name.css"

rm post_create
