#!/bin/sh

# vaccine.js must NOT be in the source list.
source_dir='{{{ SOURCE_DIR }}}'
app_name='{{{ APP_NAME }}}'


echo '(function() {"use strict";' # You can remove "use strict" if you like
cat vaccine.js   # Output vaccine.js separately

for file in $(find $source_dir -type f)
do
  name="$app_name/$(echo "$file" | sed -e "s#^$source_dir/##" -e 's/\.js//')"
  echo "define('$name', function(require, exports, module) {"
  cat $file
  echo '});'
done

echo '}());'

