#!/bin/sh

# vaccine.js must NOT be in the source list.
source_dir='{{{ SOURCE_DIR }}}'
app_name='{{{ APP_NAME }}}'
app_main_module='{{{ APP_MAIN_MODULE }}}'  # the main/index module name (don't add .js)
vaccine='{{{ VACCINE_PATH }}}'  # the location and name of the vaccine script



echo '(function() {"use strict";' # You can remove "use strict" if you like
cat $vaccine   # Output vaccine.js separately


for file in $(find $source_dir -type f)
do
  name="$app_name/$(echo "$file" | sed -e "s#^$source_dir/##" -e 's/\.js//')"
  echo "define('$name', function(require, exports, module) {"
  cat $file
  echo '});'
done

# Define the app module as the main/index file's exports.
echo "define('$app_name', function(require, exports, module) {"
echo "  module.exports = require('$app_name/$app_main_module');"
echo '});'


echo '}());'

