#!/bin/sh

# Configure the dev server, build scripts, and loader for the test sources

if test "X$1" = 'X--release'
then
  bin/vaccine configure my_app
  mv vaccines/* .
  rm -r vaccines
fi

cd test
../bin/vaccine configure test_app --src test_src --lib test_lib
mv vaccines/* .
cp vaccine.js test_src
cp vaccine.js util_src

../bin/vaccine configure test_app --src node_src --lib test_lib
cd vaccines
mv build_node ..
mv dev_server_express_node.js ..
mv dev_server_standalone_node.js ..
mv vaccine_loader.js ../vaccine_loader_node.js
cd ..

../bin/vaccine configure util --src util_src
mv vaccines/build build_util

rm -r vaccines


mkdir -p simple

make_simple() {
  type=$1
  sed "s/{{{VACCINE_TYPE}}}/$type/g" simple.html |
      sed "s/{{{EXPECTED_FAILURES}}}/$2/g" > "simple/test_$type.html"
}

make_simple vaccine 0
make_simple vaccine_loader 0
make_simple vaccine_ordered 2
make_simple vaccine_simple 3
