#!/bin/sh

# Configure the dev server, build scripts, and loader for the test sources

./configure -a my_app
mv vaccines/* .
rm -r vaccines

cd test
../configure --app test_app --main main --output test_built.js --src test_src --lib test_lib
mv vaccines/* .
cp vaccine.js test_src
cp vaccine.js util_src

../configure --app test_app --main main --output test_built_node.js --src node_src --lib test_lib --build ./build_node
cd vaccines
mv build_node ..
mv dev_server_express_node.js ..
mv dev_server_standalone_node.js ..
mv vaccine_loader.js ../vaccine_loader_node.js
cd ..

../configure --app util --src util_src
mv vaccines/build build_util

rm -r vaccines

